# The URL the site will be built for
base_url = "https://zeisch.xyz"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# The theme to use
theme = "brutalist"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
list_pages = true
